FROM php:8.1-apache

EXPOSE 80

COPY . /var/www/html

RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 754 /var/www/html

RUN docker-php-ext-install mysqli 
RUN docker-php-ext-enable mysqli 

FROM jenkins/jenkins:latest